version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: 3d-file-exporter
    command: tail -f /dev/null
    ports:
    - "8000:8000"
    volumes:
      - ./:/usr/src/app
